### ISSUE TITLE
Feature Request: traceback for Terra functions

### ISSUE THREAD

**Issue by paniq** [terralang/terra#136]
I'm currently in a situation where I do a lot of multithreading in Terra, and having line number related information in terra and especially gdb tracebacks would go a long way towards figuring out what's wrong, and which lines are actually causing trouble.

Will this ever be possible?

**Comment by zdevito** [comment]
Integration with gdb is tricky. It should work to provide stack traces on linux as long as the -g flag is provided to Terra. You can also use the -mgg flags, which will force terra to output a dynamic library to disk and use dlopen on it every time it compiles, this slows compilation down but should get the debug information transmitted to GDB correctly. Finally, terralib.traceback(nil) can be called from Terra code to generate a traceback in process, which may work for certain use-cases.

**Comment by paniq** [comment]
I tried terralib.traceback; The output only lists function entry points plus instruction pointer offset, which makes it nontrivial to figure out what line caused trouble in large functions.

**Comment by elliottslaughter** [comment]
I'm going to close this in favor of https://github.com/terralang/terra/issues/354, in theory if we get that working support for gdb/lldb should just come along "for free".
