### ISSUE TITLE
defer is not documented

### ISSUE THREAD

**Issue by brandonbloom** [terralang/terra#154]
I was looking for hints on idiomatic error handling and I found this: https://github.com/zdevito/terra/blob/8cae2a051e604b11f9ace0ee435253b8763ed5b1/tests/defer.t

If those go-style defer statements are a stable feature that can be relied on, it would be great if they were documented, however briefly.

Keywords for others looking for this: defer, exceptions, errors, try, catch, finally, scope, riia, destructor, with, close, finalize.

**Comment by Lupus** [comment]
Hey @zdevito, could you please share your opinion regarding defer in terra? We would really like to use it, but we don't feel safe relying on undocumented feature.

Is it going to be block-level as it is now or it will be transferred to function-level (as in go)? May be it is possible to shed some light on this design choice?

Thanks in advance!

**Comment by zdevito** [comment]
I think it will stay in some form. Not going to go away completely, but I
haven't used it myself much which means that exact behavior might need
tweaking. It will stay block level. The function-level go behavior requires
allocation to store the list of deferred things, which is not something
that I want to build into Terra. The intention is for it to allow C++-like
destructor behavior, but in a way that does not force you to associate the
behavior with a type.

I have a TODO to get around to documenting it and the other changes. (I am
also happy to take pull requests on the website for updated documentation
if anyone is interested. I've been working on a Terra for C programmers
comparison, as well http://terralang.org/TerraForCPP.html)

**Comment by Lupus** [comment]
Awesome, thanks for an update! TerraForCPP looks really cool, very nice way to get into terra quickly.

**Comment by bananu7** [comment]
I've spotted a couple of small mistakes 

* Loops - C++ - `for(x; y; z;)` has an extra semicolon
* Declaring functions - meta Terra - typo `reg` instead of `ret`

**Comment by ErikMcClure** [comment]
It's 2020 and this still isn't documented

**Comment by elliottslaughter** [comment]
And here we are, six years later....

https://terralang.org/getting-started.html#defer

Closing.
