### ISSUE TITLE
Update documentation to include labels (was: New Terra release)

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#173]
Would it be possible to do a Terra release? I know not a lot has changed, but the current release is missing the isconstant fix, which prevents me from using it with Regent.

**Comment by 0joshuaolson1** [comment]
Relevant: the most recent [release notes](https://github.com/zdevito/terra/releases/tag/release-2016-03-25) haven't made it to the [api](http://terralang.org/api.html) [docs](https://github.com/zdevito/terra/blob/gh-pages/api.md) yet (`label([name]) for example)`.

**Comment by elliottslaughter** [comment]
Updated, finally in df40da2390066ec5db9e66a2f86db46b48a0c8e9 and c50680c7f5c422f44255bd87ed5b87e33096254f.
