### ISSUE TITLE
avxhadd.t and sgemm.t tests failure on osx 10.12.5 sierra: LLVM ERROR: Do not know how to split the result of this operator!

### ISSUE THREAD

**Issue by glycerine** [terralang/terra#263]
~~~
MacBook-Pro ~/uns/terra-OSX-x86_64-332a506/share/terra/tests $ ../../../bin/terra run
...
avxhadd.t:
SplitVectorResult #0: 0x7fa02a023a30: v8f32 = llvm.x86.avx.hadd.ps.256 0x7fa02a023928, 0x7fa02a023820, 0x7fa02a023820 [ORD=4] [ID=0]

LLVM ERROR: Do not know how to split the result of this operator!
...
sgemm.t:
SplitVectorResult #0: 0x7fc3568a8a00: v8f32 = llvm.x86.avx.hadd.ps.256 0x7fc3568a9c10, 0x7fc3568ac368, 0x7fc3568ac368 [ORD=2] [ID=0]

LLVM ERROR: Do not know how to split the result of this operator!
~~~

**Comment by joeyo** [comment]
This continues to be true on High Sierra 10.13.3.

```
$ llvm-gcc --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by elliottslaughter** [comment]
What LLVM version does this happen on? We have new Terra binaries as part of the beta, that are linked against LLVM 6. In some cases these sorts of errors go away with newer LLVM versions.

Please go to #323 to try it out.

**Comment by elliottslaughter** [comment]
There hasn't been a response on this issue in a long time, so I'm going to close it. Our LLVM support has been updated multiple times since this was filed, so it's likely the problem does not exist any more, but at any rate, we can't fix issues without someone stepping up to test them.
