### ISSUE TITLE
cuda error 500 on CUDA 9.0 and LLVM 3.8

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#288]
Reposting a bug report from @chichengumich in [this comment](https://github.com/zdevito/terra/pull/278#issuecomment-399790307):

> Hi, I was trying to compile terra with CUDA 9.0 and llvm 3.8. The compliation went through without any error. However, when I tried to run cudahello.t, it returns
> ```
> cudahello.t:21: cuModuleGetFunction: cuda reported error 500
> stack traceback:
> 	[C]: in function 'error'
> 	[string "<string>"]:247: in function 'cudacompile'
> 	cudahello.t:21: in main chunk
> ```
> Is there any solution?

**Comment by elliottslaughter** [comment]
@chichengumich Can you please reply with enough information so that we can reproduce your bug? What OS and OS version? C++ compiler and version? How did you obtain LLVM (build from source, binary (if so from where?), etc.).

Also, can you confirm if your machine has a GPU attached?

I asked @manopapad to reproduce your bug, and we weren't able to do it with either CUDA 8.0 or 9.0. So it would appear that there's something specific to your setup that is problematic.

Thanks.

**Comment by chichengumich** [comment]
@elliottslaughter Thank you for your response!
I am using ubuntu 16.04 LTS.
For compiler I have clang 3.8, 3.9 and 6.0 installed. The default is clang 3.8:
They are all installed using `sudo apt-get install clang-3.8` and then `sudo apt-get install libclang-3.8-dev`.
For CUDA, I have CUDA 8.0, 9.0 and 9.1 installed. CUDA_HOME is set to 
```
$ echo $CUDA_HOME
/usr/local/cuda-9.0
$ ls -la /usr/local | grep cuda
lrwxrwxrwx  1 root root   19 Jun 24 16:32 cuda -> /usr/local/cuda-8.0
drwxr-xr-x 17 root root 4096 Jun 24 16:32 cuda-8.0
drwxr-xr-x 18 root root 4096 Feb 26 10:15 cuda-9.0
drwxr-xr-x 19 root root 4096 Feb 26 10:05 cuda-9.1

```
I have a GTX1070 attached, with my regular CUDA program compiles and running correctly. I also have a copy of Opt installed in a separate `Optlang/Opt` and `Optlang/terra' installed. In which terra is installed [terra-2016-03-25](https://github.com/zdevito/terra/releases/download/release-2016-03-25/terra-Linux-x86_64-332a506.zip)
```
hicheng@ccubuntu:~$ ls -la /usr/bin | grep clang
lrwxrwxrwx  1 root root          25 Jun 21  2016 clang -> ../lib/llvm-3.8/bin/clang
lrwxrwxrwx  1 root root          27 Jun 21  2016 clang++ -> ../lib/llvm-3.8/bin/clang++
lrwxrwxrwx  1 root root          25 Jul 12  2016 clang-3.8 -> ../lib/llvm-3.8/bin/clang
lrwxrwxrwx  1 root root          27 Jul 12  2016 clang++-3.8 -> ../lib/llvm-3.8/bin/clang++
lrwxrwxrwx  1 root root          25 Jul 26  2017 clang-3.9 -> ../lib/llvm-3.9/bin/clang
lrwxrwxrwx  1 root root          27 Jul 26  2017 clang++-3.9 -> ../lib/llvm-3.9/bin/clang++
lrwxrwxrwx  1 root root          25 Jun  4 18:39 clang-6.0 -> ../lib/llvm-6.0/bin/clang
lrwxrwxrwx  1 root root          27 Jun  4 18:39 clang++-6.0 -> ../lib/llvm-6.0/bin/clang++
lrwxrwxrwx  1 root root          44 Jun 21  2016 clang-apply-replacements -> ../lib/llvm-3.8/bin/clang-apply-replacements
lrwxrwxrwx  1 root root          44 Jul 12  2016 clang-apply-replacements-3.8 -> ../lib/llvm-3.8/bin/clang-apply-replacements
lrwxrwxrwx  1 root root          44 Jul 26  2017 clang-apply-replacements-3.9 -> ../lib/llvm-3.9/bin/clang-apply-replacements
lrwxrwxrwx  1 root root          31 Jun 21  2016 clang-check -> ../lib/llvm-3.8/bin/clang-check
lrwxrwxrwx  1 root root          31 Jul 12  2016 clang-check-3.8 -> ../lib/llvm-3.8/bin/clang-check
lrwxrwxrwx  1 root root          31 Jul 26  2017 clang-check-3.9 -> ../lib/llvm-3.9/bin/clang-check
lrwxrwxrwx  1 root root          28 Jul 12  2016 clang-cl-3.8 -> ../lib/llvm-3.8/bin/clang-cl
lrwxrwxrwx  1 root root          28 Jul 26  2017 clang-cl-3.9 -> ../lib/llvm-3.9/bin/clang-cl
lrwxrwxrwx  1 root root          29 Jun  4 18:39 clang-cpp-6.0 -> ../lib/llvm-6.0/bin/clang-cpp
lrwxrwxrwx  1 root root          39 Jul 26  2017 clang-include-fixer-3.9 -> ../lib/llvm-3.9/bin/clang-include-fixer
lrwxrwxrwx  1 root root          31 Jun 21  2016 clang-query -> ../lib/llvm-3.8/bin/clang-query
lrwxrwxrwx  1 root root          31 Jul 12  2016 clang-query-3.8 -> ../lib/llvm-3.8/bin/clang-query
lrwxrwxrwx  1 root root          31 Jul 26  2017 clang-query-3.9 -> ../lib/llvm-3.9/bin/clang-query
lrwxrwxrwx  1 root root          32 Jul 12  2016 clang-rename-3.8 -> ../lib/llvm-3.8/bin/clang-rename
lrwxrwxrwx  1 root root          32 Jul 26  2017 clang-rename-3.9 -> ../lib/llvm-3.9/bin/clang-rename
lrwxrwxrwx  1 root root          32 Jun 21  2016 clang-tblgen -> ../lib/llvm-3.8/bin/clang-tblgen
lrwxrwxrwx  1 root root          32 Jul 26  2017 clang-tblgen-3.9 -> ../lib/llvm-3.9/bin/clang-tblgen
lrwxrwxrwx  1 root root          44 Jul 12  2016 scan-build-3.8 -> ../share/clang/scan-build-3.8/bin/scan-build
lrwxrwxrwx  1 root root          44 Jul 26  2017 scan-build-3.9 -> ../share/clang/scan-build-3.9/bin/scan-build
lrwxrwxrwx  1 root root          47 Jul 26  2017 scan-build-3.9-py -> ../share/clang/scan-build-3.9/bin/scan-build-py
lrwxrwxrwx  1 root root          42 Jul 12  2016 scan-view-3.8 -> ../share/clang/scan-view-3.8/bin/scan-view
lrwxrwxrwx  1 root root          42 Jul 26  2017 scan-view-3.9 -> ../share/clang/scan-view-3.9/bin/scan-view

```

**Comment by chichengumich** [comment]
Hi @manopapad,
After further inspection, I found terra binay is neither linked to libcuda.so or libcudart.so. However, when I tried the binary of terra downloaded from [](https://github.com/zdevito/terra/releases), it also does not link to any cuda runtime. Yet, the binary distribution of terra works if I set my CUDA_HOME to CUDA-8.0(dose not work if set to CUDA-9.0).
I'm curious about how terra interact with CUDA.

**Comment by manopapad** [comment]
It looks like terra locates libcuda.so dynamically at runtime, and loads it into memory:

https://github.com/zdevito/terra/blob/master/src/terralib.lua#L4030-L4048
https://github.com/zdevito/terra/blob/master/src/cudalib.lua#L14-L15

My understanding after inspecting this code is that terra should be able to load any version of CUDA, so long as CUDA_HOME is set to the appropriate directory. If that's not working for you, you could add debugging output around these lines to see if terra is inferring the paths correctly.

**Comment by chichengumich** [comment]
@manopapad 
Thanks for your hint! I found `cuModuleGetFunction` is related to CUDA driver API, instead of CUDA runtime API. Which means this is potentailly unrelated to CUDA toolkit version (8.0, 9.0 etc). Instead it's related to driver versions. I'm currently using 390.25 version of driver. Could you provide your driver version?
If possible, could you also test my version of driver in your machine to reproduce this problem?

**Comment by chichengumich** [comment]
Hi, @Algomorph @manopapad @elliottslaughter 
After constant trail and error, I found the root cause is my version of llvm library. Compiling with LLVM 3.5 library worked for both CUDA 8.0, CUDA 9.0 and CUDA 9.1 on my machine. Note that due to calling convention problem, the actual compiler used to compile this project have to be ubuntu default gcc or clang 3.8+.

**Comment by elliottslaughter** [comment]
@chichengumich Sorry this has been taking so much of your time.

I was able to reproduce on Ubuntu 16.04, LLVM 3.8, and CUDA 9.2. This is a bit odd since I'm pretty sure we've been testing LLVM 3.8 with various CUDA versions on supercomputers. However, those are generally different Linux distros (not Ubuntu).

I modified the error reporting so at least we can see the error string now:

`tests/cudahello.t:21: cuModuleGetFunction: cuda reported error 500: named symbol not found`

Though I'm not sure how much additional light this sheds on the problem.

I confirmed this was happening in this call: https://github.com/zdevito/terra/blob/master/src/cudalib.lua#L298

I'm out of time for the moment, but maybe someone can use this to figure out what's going on.

**Comment by Algomorph** [comment]
@elliottslaughter , @manopapad ,
I got the same problem on Ubuntu 16.04, LLVM 4.0, and CUDA 9.2.
Sorry, I've never done any lua coding before and I don't know how to test the paths here: 
[https://github.com/zdevito/terra/blob/master/src/terralib.lua#L4030-L4048](https://github.com/zdevito/terra/blob/master/src/terralib.lua#L4030-L4048)

I added some print statements, but I know when and how am I supposed to see the output (during build? During run? Run of which files, and how?). Sorry, I've never worked with Terra before so I don't know the basics, just trying to get it working on my platform for the first time...

**Comment by Algomorph** [comment]
P.S. For me, using LLVM 3.5 like @chichengumich worked. Only one test failed:

> =================
> = FAILING tests
> =================
> expvec.t
> =================

**Comment by cinterloper** [comment]
Is this at all related?
https://github.com/numba/numba/issues/2975
"For the past few CUDA releases, NVVM has supported IR input either in LLVM 3.4 text IR format or LLVM [later version] bitcode IR format. As of CUDA 9.2, the bitcode IR format is based on LLVM 5.0."

"There have been warnings in the last few CUDA releases that the text IR option (which has not been update for some time) is deprecated and will be dropped in a future CUDA release. See nvvmAddModuleToProgram, for an example."

**Comment by elliottslaughter** [comment]
I don't think that's related to this specific issue, because you'll at the top of the issue that @chichengumich tested CUDA 8.0, 9.0 and 9.1 before moving to 9.2.

However, if it's true what is said in that issue, we will need to move to LLVM 5.0. I will open another issue so this point does not get lost.

**Comment by elliottslaughter** [comment]
@chichengumich I've got a patch here that might fix this issue: #325

Also, we've since added support for both LLVM 5 and 6 in master.

If you still care about this, would you mind testing one or the other of these, to see if they fix your problem? Thanks.

**Comment by chichengumich** [comment]
@elliottslaughter 
Thanks! Glad that you got it fixed. I will try it once I have time.

**Comment by gilbo** [comment]
I'm having the same bug with the following setup:
Ubuntu 16.04
NVidia Driver 375.26
LLVM 3.9.0
Cuda 8.0

I have tried using LLVM 3.8.0 instead, which results in compiler errors during Terra's build

**Comment by elliottslaughter** [comment]
When you switched from 3.9 to 3.8, did you start from a completely fresh clone? (Or something similarly aggressive like "git clean -fxd", though I don't recommend that.)

In my experience "make clean" doesn't get rid of all the LLVM build artifacts so you end up with a broken build if you switch LLVMs and don't reclone (or similar).

3.9 should work, just not with CUDA. For the best CUDA support, I recommend 3.8 or 6.0. If you don't have a specific preference I'd probably start with 3.8 because that's what we have been running on supercomputers for a long while now.

**Comment by gilbo** [comment]
Same set of linker errors trying to build against

Ubuntu 16.04
NVidia Driver 375.26
LLVM 3.8.0
Cuda 8.0

even with a new clone of the Terra repository.  The LLVM directory is straight from the binaries hosted on their website.

```
g++ build/main.o build/linenoise.o -o release/bin/terra -g -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive  -ldl -pthread
release/lib/libterra.a(tcompiler.o): In function `terra_inittarget(lua_State*)':
/home/gilbo/terra/src/tcompiler.cpp:317: undefined reference to `llvm::sys::getProcessTriple[abi:cxx11]()'
release/lib/libterra.a(tcompiler.o): In function `FindLinker(terra_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
/home/gilbo/terra/src/tcompiler.cpp:2844: undefined reference to `llvm::sys::findProgramByName[abi:cxx11](llvm::StringRef, llvm::ArrayRef<llvm::StringRef>)'
release/lib/libterra.a(tllvmutil.o): In function `llvmutil_disassemblefunction':
/home/gilbo/terra/src/tllvmutil.cpp:105: undefined reference to `llvm::sys::getProcessTriple[abi:cxx11]()'
release/lib/libterra.a(tcwrapper.o): In function `clang::QualType::getAsString[abi:cxx11](clang::SplitQualType)':
/home/liszt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04/include/clang/AST/Type.h:905: undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::Type const*, clang::Qualifiers)'
release/lib/libterra.a(tcwrapper.o): In function `clang::NamedDecl::getNameAsString[abi:cxx11]() const':
/home/liszt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04/include/clang/AST/Decl.h:184: undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
release/lib/libterra.a(tcwrapper.o): In function `IncludeCVisitor::GetFields(clang::RecordDecl*, Obj*)':
/home/gilbo/terra/src/tcwrapper.cpp:101: undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
release/lib/libterra.a(tcwrapper.o): In function `IncludeCVisitor::TraverseFunctionDecl(clang::FunctionDecl*)':
/home/gilbo/terra/src/tcwrapper.cpp:431: undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
release/lib/libterra.a(tcwrapper.o): In function `LuaOverlayFileSystem::GetFile(llvm::Twine const&, clang::vfs::Status*, llvm::StringRef*)':
/home/gilbo/terra/src/tcwrapper.cpp:661: undefined reference to `llvm::Twine::str[abi:cxx11]() const'
/home/gilbo/terra/src/tcwrapper.cpp:687: undefined reference to `llvm::Twine::str[abi:cxx11]() const'
release/lib/libterra.a(tcwrapper.o): In function `LuaOverlayFileSystem::openFileForRead(llvm::Twine const&)':
/home/gilbo/terra/src/tcwrapper.cpp:731: undefined reference to `llvm::Twine::str[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
Makefile:250: recipe for target 'release/bin/terra' failed
make: *** [release/bin/terra] Error 1
```

Scanning them again real quick it seems like maybe a C++11 flag is the whole issue here?  I'm not exactly sure how to set that appropriately in the build system.

**Comment by elliottslaughter** [comment]
If you want to use the binaries you could try compiling with `-D_GLIBCXX_USE_CXX11_ABI=0`.

Personally though, this is why I always build LLVM from source. There are too many things that can break if you don't have exactly the same system and flags, and from-source builds, while time consuming, nearly always work out of the box.

**Comment by gilbo** [comment]
I’ll give the flag a go. Thanks.

My impression with building LLVM from source is that there are even more ways that can go wrong; even more options I don’t understand.

― Gilbert

**Comment by gilbo** [comment]
FYI, compiling with -D_GLIBCXX_USE_CXX11_ABI=0 produces a different set of unresolved name errors.

```
g++ build/main.o build/linenoise.o -o release/bin/terra -g -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive  -ldl -pthread
release/lib/libterra.a(tcompiler.o): In function `terra_inittarget(lua_State*)':
/home/gilbo/terra/src/tcompiler.cpp:355: undefined reference to `llvm::TargetRegistry::lookupTarget(std::string const&, std::string&)'
release/lib/libterra.a(tcompiler.o): In function `llvm::sys::DynamicLibrary::LoadLibraryPermanently(char const*, std::string*)':
/home/liszt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04/include/llvm/Support/DynamicLibrary.h:78: undefined reference to `llvm::sys::DynamicLibrary::getPermanentLibrary(char const*, std::string*)'
release/lib/libterra.a(tllvmutil.o): In function `llvmutil_disassemblefunction':
/home/gilbo/terra/src/tllvmutil.cpp:111: undefined reference to `llvm::TargetRegistry::lookupTarget(std::string const&, std::string&)'
release/lib/libterra.a(tllvmutil.o): In function `llvmutil_executeandwait(std::string, char const**, std::string*)':
/home/gilbo/terra/src/tllvmutil.cpp:406: undefined reference to `llvm::sys::ExecuteNoWait(llvm::StringRef, char const**, char const**, llvm::StringRef const**, unsigned int, std::string*, bool*)'
release/lib/libterra.a(tcwrapper.o): In function `dofile(terra_State*, TerraTarget*, char const*, char const**, char const**, Obj*)':
/home/gilbo/terra/src/tcwrapper.cpp:897: undefined reference to `clang::CreateLLVMCodeGen(clang::DiagnosticsEngine&, std::string const&, clang::HeaderSearchOptions const&, clang::PreprocessorOptions const&, clang::CodeGenOptions const&, llvm::LLVMContext&, clang::CoverageSourceInfo*)'
collect2: error: ld returned 1 exit status
Makefile:250: recipe for target 'release/bin/terra' failed
make: *** [release/bin/terra] Error 1
```

**Comment by gilbo** [comment]
So, a solution to the linking C++11 issues (but not the CUDA issues) is the following:

Ensure that the Makefile uses the same `clang` compiler that `terra` is being built against by changing these lines:
```
CXX ?= $(CLANG)++
CC ?= $(CLANG)
```

I removed the question marks.  Some other conditional logic could be used instead.  I believe this was the intention of the Makefile to begin with, so it may be a good fix for C++11 ABI troubles more generally.

**Comment by gilbo** [comment]
Ahh, interesting!  I now have all the CUDA tests passing, but the tests tend to hang for a while on something or another.  I'm getting similar behavior with invoking `nvidia-smi` so it may just be some jankyness with my driver installation...

Ahh, the issue is persistence mode [https://devtalk.nvidia.com/default/topic/1011192/cuda-setup-and-installation/nvidia-smi-is-slow-on-ubuntu-16-04-/](persistence mode), so I ought to be able to fix that.  Looks like I'm good to go.  I'll leave this issue open for @cheng-chi to confirm.

**Comment by elliottslaughter** [comment]
This was a long-running comment thread and I'm not sure we ever got a replication with a newer LLVM (at least version 5). I've done a lot of tests in the meantime with newer Ubuntu and CUDA versions (e.g., just recently with 20.04 and CUDA 11). As a result, I think this has long-since been fixed, but if not, it's probably time to start a new issue anyway to avoid growing the clutter.
