### ISSUE TITLE
Build fails on Ubuntu 16.04 if curses is not installed

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#307]
Building Terra fails on Ubuntu 16.04 if `libncurses5-dev` is not installed. Currently the workaround for this is to just install that package, but it would be nice to detect this and stop linking curses.

Place the following into `Dockerfile` and run `docker build .`:

```
FROM ubuntu:16.04

RUN apt-get update -qq && \
    apt-get install -qq \
      build-essential git wget \
      clang-3.5 libclang-3.5-dev llvm-3.5-dev && \
    apt-get clean

RUN git clone -b master https://github.com/zdevito/terra.git && \
    cp -r terra terra35 && \
    LLVM_CONFIG=llvm-config-3.5 make -C terra35 REEXPORT_LLVM_COMPONENTS="irreader jit mcjit x86" && \
    mkdir /usr/local/terra35 && \
    make -C terra35 install PREFIX=/usr/local/terra35
```

Fails with:

```
g++ build/main.o build/linenoise.o -o release/bin/terra -g -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive  -lcurses  -lz -ldl -pthread
/usr/bin/ld: cannot find -lcurses
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [release/bin/terra] Error 1
```

**Comment by Qix-** [comment]
This is happening for me _even with_ `libncurses5-dev` on both 18.04 and 19.04.

**Comment by Qix-** [comment]
Sorry, I should be more clear - ncurses is required when linking against the distributed `libterra.a` archive.

**Comment by elliottslaughter** [comment]
I'm going to consider this fixed by way of documentation (which I have updated). Unfortunately, I don't think we're in a position to fix Ubuntu's packages, so we're sort of stuck with what we've got.
