### ISSUE TITLE
Please document `__for` (and question about iterators)

### ISSUE THREAD

**Issue by capr** [terralang/terra#333]
Hi!

Please document `__for`, it's very useful.

Related question: can I implement custom iterators myself that are not tied to a specific type, eg. can I implement a generic `foreach(any_type, body_macro)` that calls say the method `__next` on the type?

Thanks!

**Comment by capr** [comment]
The reason for asking this in relation to `__for` is because I'm converting some Lua code to Terra and I have some closures that tap into their outer scope a lot, and I don't know how to convert those, since Terra doesn't have closures (so functions can't see into the lexical scope of the function definition), and macros are hygenic (so macros can't see into the lexical scope at the call site). But somehow Terra _can_ construct a quote out of the for body and pass it to the `__for` metamethod. I think I need a similar mechanism. 

Eg, consider the following: 
~~~
iterate = macro(function(i, j, body)
	return quote
		for i = i, j do
			[ body(i) ]
		end
	end
end)

terra f()
	iterate(1, 3, [ macro(function(i)
		return `printf('%d\n', i)
	end) ])
end
f()
~~~

**Comment by capr** [comment]
Update: I made that example work:
~~~
iterate = macro(function(i, j, body)
	return quote
		for i = i, j do
			body(i)
		end
	end
end)

terra f()
	var x = 5
	iterate(1, 3, [macro(function(i)
			return `printf('%d %d\n', x, i)
		end)])
end
f()
~~~
So now I have a macro that can see `x` and use it as a callback for another macro. That solves the custom iterator requirement. 

The next thing I tried was to save the callback macro into a Lua variable so I can call it later like I would call a closure. That din't work: "cannot define global variables or assign to upvalues in an escape" :(

**Comment by aiverson** [comment]
Something you might want to do instead is write a macro that accepts an expression and then produces something with __for for the loop.

```
local makeitertype = terralib.memoize(function(basetype)
  local struct iterImpl {
    base: basetype
  }
  iterImpl.metamethods.__for = function(self, body)
    return quote
      while not self.base:__done() do
        [body(`self.base:__next())]
      end
    end
  end
  return iterImpl
end)
iterate = macro(function(baseexpr)
  return `[makeitertype(baseexpr:gettype())]{baseexpr}
end

-- then in terra
for i in iterate(something) do
  printf('%d\n', i)
end
```
I have not tested this code, but hopefully it makes sense.

**Comment by ErikMcClure** [comment]
It's been almost 2 years and __for still isn't documented. This is absurd.

**Comment by elliottslaughter** [comment]
Finally documented in c22e00f036bca6c8a640b42332b66e8a9866c27c.
