### ISSUE TITLE
Expose checkreturns() from terralib

### ISSUE THREAD

**Issue by capr** [terralang/terra#339]
Hi!

Please document `lex:terraexpr()` and `lex:terrastats()` and expose the `checkreturns()` helper in the API because it is needed for inferring the return type when generating terra functions from scratch.

**Comment by elliottslaughter** [comment]
Can't you infer a return type by doing something like:

```
function check_return(expr)
  local terra helper()
    return expr
  end
  return helper:gettype().returntype
end
local ok, return_type = pcall(check_return, expr)
```

(Modulo free variables in expr, obviously, but you get the idea.)

I use this basic pattern to infer what I need about the Terra type system in extension languages like Regent, without using any internal APIs.

**Comment by elliottslaughter** [comment]
I've updated the documentation. Closing this issue assuming the workaround is sufficient for type checking, but feel free to open if it's not sufficient.
