### ISSUE TITLE
RFC: Deprecate support for LLVM <= 3.4

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#353]
I'd like to propose deprecating support for LLVM versions <= 3.4. LLVM 3.4 is 5 years old now, and I don't think it is widely used in the Terra community. But there is `#ifdef`'d code in Terra to support at least as far back as 3.1.

Deprecation wouldn't have any immediate impact, except to explicitly say that we would not consider it a semver breaking change to remove it in a future minor version of Terra. (So we could remove support in 1.0 or 1.1, but not 1.0.1.)

We would still want to decide on a LLVM compatibility policy moving forward. I think 5 years of support is pretty generous. Of course we can still choose to support some versions longer than that (e.g. we can't currently remove 3.5 because we don't have an alternative for debug symbol support).

Please respond to this issue if you have any concerns in deprecating or removing support for LLVM <= 3.4.

**Comment by aiverson** [comment]
I am in favor of dropping LLVM <= 3.4 immediately or as soon as possible without breaking versioning. What is required to get debug info running on a newer version of terra?

**Comment by elliottslaughter** [comment]
We're pre-1.0 at the moment, so strictly speaking we can do whatever we want at this point, including removing support outright if no one needs it. Post-1.0 we'll probably want to have an explicit stability policy to say what we're committing to keeping stable.

For debug symbol support, you can run `git log --graph --decorate --oneline master..develop` and grep for `debug`. There was some work in progress by @zdevito that is probably just worth pulling in, assuming it doesn't cause a lot of churn. However, if I'm reading the commit messages correctly, that only gets us up to LLVM 3.8. In general, I believe debug symbols are controlled by metadata on the LLVM IR, and seems to break more frequently than other aspects of LLVM. I don't think there is a general recipe for what to do except to run Clang and see what LLVM IR it spits out, and try to reverse engineer that.

**Comment by aiverson** [comment]
Is there any chance that including C++ header support in terra would be a simple change? Because if we can include the lldb public C++ api, we can get more use out of the debug information. I'll see if I can figure out getting the debug information to work. I don't have that much experience using LLVM directly, but I'll see what I can do.

**Comment by elliottslaughter** [comment]
Let's split the debug / C++ discussion into a separate thread, I think this will be move involved.

**Comment by jameshegarty** [comment]
No objections from me! I don't rely on anything from these old versions of LLVM, and support making maintenance easier :)

**Comment by elliottslaughter** [comment]
I'm going to go ahead and consider LLVM 3.4 and earlier to be hereby deprecated, but it may take some time to work all of the old code out of the Terra code base.

**Comment by elliottslaughter** [comment]
Merged via #424.
