### ISSUE TITLE
Find new CI platform

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#355]
Re: https://news.ycombinator.com/item?id=19218036

Not urgent, but probably not worth sticking around in the Travis community given what's going on. I'm leaning toward Circle CI, but suggestions welcome.

**Comment by ProfFan** [comment]
It appears that Travis is gone?

**Comment by elliottslaughter** [comment]
It should be here now: https://travis-ci.org/terralang/terra/builds

I will update the badges on the README.

**Comment by elliottslaughter** [comment]
This is somewhat more urgent now due to a recent pricing change:

  * https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
  * https://news.ycombinator.com/item?id=24964601

Needing to regularly reapply for credits does not sound like fun to me. Maybe it's time to dust off Github Actions and see if we can switch to it for all of our build needs.

**Comment by elliottslaughter** [comment]
This keeps getting worse:

https://news.ycombinator.com/item?id=25338983

For now we're fine, but it's possible that this could become urgent in a hurry if we run out of credits and are unable to get more.

**Comment by elliottslaughter** [comment]
Apparently I misunderstood. travis-ci.org is being terminated *completely*. In order to continue, you have to migrate your project (manually?) to travis-ci.com.

https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions

One way or another we have to do something by December 31.

**Comment by elliottslaughter** [comment]
I went ahead and merged #436 after finally getting it up to parity with Travis. We now have Github Actions support in master.

There isn't really any reason to remove Travis, but once December 31 passes I don't anticipate going to any effort to revive it.

**Comment by elliottslaughter** [comment]
This is now complete. We moved to Github Actions for Mac and Linux.
