### ISSUE TITLE
Can't compile fgets()?

### ISSUE THREAD

**Issue by vultraz168** [terralang/terra#359]
Example:
```
C = terralib.includec("stdio.h");

terra main()
	var buffer : int8[2048];
	C.fgets(buffer, 2048, C.stdin);
end

terralib.saveobj("fgets", {main = main});
```

Error:
```
Call parameter type does not match function signature!
  %1 = load %struct._IO_FILE*, %struct._IO_FILE** @stdin
 %"type 0x5b62b70"*  %2 = call i8* @fgets(i8* %0, i32 2048, %struct._IO_FILE* %1)
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by elliottslaughter** [comment]
Can you post a complete example, and also tell us what LLVM/Terra/OS version you're on?

Thanks.

**Comment by aiverson** [comment]
It looks like you might need to dereference C.stdin before passing it into fgets.

**Comment by aiverson** [comment]
I tested your code exactly as it appeared with the addition of including the stdio library, and it worked on my machine. What system and version are you using?

**Comment by vultraz168** [comment]
I'm on Gentoo Linux using LLVM 7; I used the Terra binary from https://github.com/zdevito/terra/releases because I can't get it to compile right now.

**Comment by vultraz168** [comment]
Managed to compile Terra and get my program working again with some fiddling. It works now.

**Comment by aiverson** [comment]
That's good to hear.

**Comment by elliottslaughter** [comment]
I think what's happening here is that Terra's process for gathering internalized files is capturing headers on the build machine that then aren't compatible with the machine you're running on. Unfortunately, I think this means that Terra binaries aren't compatible across distros in general. It may be possible to review the internalized file build procedure and see if we could do the same by another method; this isn't really an area of Terra I have much insight into.

https://github.com/zdevito/terra/blob/master/src/geninternalizedfiles.lua

**Comment by elliottslaughter** [comment]
@vultraz168 I'd be interested to know what build error you hit and what you did to fix it, if you don't mind sharing.

**Comment by elliottslaughter** [comment]
Closing for now, but if there are any further issues, feel free to reopen or open a new one.
