### ISSUE TITLE
Add support for LLVM 8

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#362]
@ProfFan @MaskRay Any takers?

https://lists.llvm.org/pipermail/llvm-announce/2019-March/000082.html

**Comment by aiverson** [comment]
I would like the ability to target WASM with terra code. This would be a convenient thing to have. I'll take a look at this if no one else has the time to implement it.

**Comment by ProfFan** [comment]
Would like to but I think I would be busy for ~3 months.

**Comment by elliottslaughter** [comment]
Merged with #419.
