### ISSUE TITLE
RFC: Deprecate NMake build on Windows

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#403]
Related to #383, now that we support CMake on Windows it would be nice to get rid of the old NMake build, particularly because NMake is even less full-featured than regular Make is.

As far as I know the CMake build on Windows is full-featured, so I'm not aware of any reason to put this off except to give time to let the CMake build get tested in the wild.

Windows users: please test CMake now and make sure it works for you.

**Comment by slaughterj** [comment]
> 
> 
> Related to #383, now that we support CMake on Windows it would be nice to get rid of the old NMake build, particularly because NMake is even less full-featured than regular Make is.
> 
> As far as I know the CMake build on Windows is full-featured, so I'm not aware of any reason to put this off except to give time to let the CMake build get tested in the wild.
> 
> Windows users: please test CMake now and make sure it works for you.

I have attempted to try the CMake build on windows, unfortunately I'm not that well versed in its usage and do not know how to let it know how to find the llvm+clang I've built from source and/or the one from https://github.com/Mx7f/llvm-package-windows/releases. I know about the find package
script but am assuming that it's just for llvm+clang installed through the windows installer?

**Comment by elliottslaughter** [comment]
You can use the variable [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html) to hint to CMake where it should look for LLVM. You can just point that to whatever directory you unpacked or installed LLVM to.

You also currently need to specify `-DTERRA_SLIB_INCLUDE_LLVM=OFF -DTERRA_SLIB_INCLUDE_LUAJIT=OFF` when you run CMake (I should really make these the default on Windows so you don't need to remember this).

**Comment by elliottslaughter** [comment]
Please see the instructions at https://github.com/terralang/terra#building-terra and reply if the Windows instructions are missing anything.

**Comment by elliottslaughter** [comment]
Similar to https://github.com/terralang/terra/issues/383, I'm planning on going forward with this. Speak now if you have any objections. The implications will be similar to what I've outlined at the top of #383, except I may do the final removal even more quickly since NMake is such a hacky build system, even more than Make.

**Comment by elliottslaughter** [comment]
I'm going to consider NMake hereby deprecated. I pushed a formal deprecation notice to `CHANGES.md`.

**Comment by elliottslaughter** [comment]
NMake has been formally deprecated for about 10 months now, and this issue was first submitted nearly 18 months ago. I'm planning on finally going through with the removal of NMake support, most likely at the same time as I remove LLVM 3.5 (see https://github.com/terralang/terra/issues/456). I never heard any objections to this issue, but certainly if there are any, let me know.

**Comment by ErikMcClure** [comment]
I haven't tried recently, but I know i've managed to compile terra using cmake on windows, so I don't rely on nmake anymore anyway, and even if the cmake file ends up getting messy I can probably fix it.

**Comment by elliottslaughter** [comment]
The PR to finally remove this code is at #489. I should still do a release beforehand so that we have a definitive "last supported" point for this code before it's removed though.

**Comment by elliottslaughter** [comment]
#489 has been merged and this code has finally been removed. The last supported release was 1.0.0-beta3.
