### ISSUE TITLE
Test problems on 1.0.0.-beta2

### ISSUE THREAD

**Issue by hissssst** [terralang/terra#451]
Distro: Arch
Terra: 1.0.0.-beta2 linux .zip

[result.txt](https://github.com/terralang/terra/files/4854527/result.txt)

**Comment by elliottslaughter** [comment]
It's a failure in `dynlib.t` and seems to be failing to link ncurses. If you go to `dynlib.t` and modify line 46 to include `"-lncurses"` in `flags`, does it go away?

**Comment by hissssst** [comment]
```terra
local flags = terralib.newlist {"-Wl,-rpath,"..libpath,libpath.."/"..libname,"-lncurses"}
local flags = terralib.newlist {"-lncurses,-Wl,-rpath,"..libpath,libpath.."/"..libname}
```

Did it both ways and test is still failing

**Comment by elliottslaughter** [comment]
This is a typo:

```
local flags = terralib.newlist {"-lncurses,-Wl,-rpath,"..libpath,libpath.."/"..libname}
```

Should be:

```
local flags = terralib.newlist {"-lncurses","-Wl,-rpath,"..libpath,libpath.."/"..libname}
```

**Comment by hissssst** [comment]
```terra
local flags = terralib.newlist {"-lncurses","-Wl,-rpath,"..libpath,libpath.."/"..libname}
```
Did it this way, still fails

**Comment by elliottslaughter** [comment]
Ok, can you attach repro instructions? Ideally something I can run in a fresh Docker container so that I can see the exact steps to get to the error you're hitting.

**Comment by hissssst** [comment]
Fixed this bug. Problem was with different versions of these two packages
```bash
$ pacman -Qs ncurses
local/ncurses 6.2-1
    System V Release 4.0 curses emulation library
local/ncurses5-compat-libs 6.2-1
    System V Release 4.0 curses emulation library, ABI 5
```

Closing
