### ISSUE TITLE
anyway to export symbols from DLL on windows?

### ISSUE THREAD

**Issue by fastcoding** [terralang/terra#462]
the codes below can produce dll, but cannot export test function. 
```lua
local C=terralib.includec'stdio.h' 
terra test() 
  C.printf('hello world\n') 
end
terralib.saveobj('test.dll',{test=test})  
```
--------------
dumpbin /exports test.dll  ( no exports at all )

**Comment by ErikMcClure** [comment]
Exports on windows are always a bit messy, you can attempt to force the linker to do this for you by passing the `/EXPORT:symbolname` argument through to the linker, but I'm not sure if this will work.

**Comment by fastcoding** [comment]
Just tested, it works!  This is an option provided by microsoft linker, that means clang will launch link.exe to do that job. thanks for your help.

> Exports on windows are always a bit messy, you can attempt to force the linker to do this for you by passing the `/EXPORT:symbolname` argument through to the linker, but I'm not sure if this will work.
