### ISSUE TITLE
LLVM 6 doesn't work with CUDA 8 and fermi

### ISSUE THREAD

**Issue by manopapad** [terralang/terra#467]
If I build on sapling (whose GPU architecture is fermi) with LLVM 6 and CUDA 8 and try to run any CUDA test, that fails with
`error 209: no kernel image is available for execution on the device`. It sounds like Terra is not producing PTX for the correct architecture.

Here is some debug output that shows where the failure is happening:

```
n0000:~/legion/language/terra> ./terra tests/cudaconst2.t
cudalib.compile: entering
cudalib.compile: picked version 20
cudalib.toptx: entering
cudalib.toptx: found libdevice libdevice.compute_20.10.bc
cudalib.toptx: found libdevice libdevice.compute_30.10.bc
cudalib.toptx: found libdevice libdevice.compute_35.10.bc
cudalib.toptx: found libdevice libdevice.compute_50.10.bc
cudalib.toptx: picked libdevice version 20 at /usr/local/cuda-8.0/nvvm/libdevice/libdevice.compute_20.10.bc
cudalib.toptx: exiting
cudalib.compile: loader call failed
tests/cudaconst2.t:15: cuModuleLoadData: cuda reported error 209: no kernel image is available for execution on the device
stack traceback:
	[C]: in function 'error'
	[string "<string>"]:253: in function 'cudacompile'
	tests/cudaconst2.t:15: in main chunk
```

**Comment by elliottslaughter** [comment]
Thanks, this is worth keeping in mind for a potential LLVM 3.8 deprecation. I hope we can eventually decommission sapling (since fermi/CUDA 8 are both quite old), but in the mean time it might be good to check what the maximum LLVM version is for sapling so that we don't break that.

**Comment by elliottslaughter** [comment]
(I don't think it's worth fixing this per se, due to the age of CUDA 8 and fermi. But I'd like to at least avoid breaking this use case while sapling is still in active use.)

**Comment by elliottslaughter** [comment]
I'm going to close this because we've moved away from the Fermi nodes on Sapling, and NVIDIA support for the architecture has been long-since end-of-life'd.
