### ISSUE TITLE
Dynamic linked Terra breaks tests in LLVM 9-11

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#477]
Documenting this so I can move on with the LLVM 10/11 merge.

Errors look like (for example):

```
513/536 Test #514: unm.t ............................Subprocess aborted***Exception:   0.14 sec
: CommandLine Error: Option 'vector-library' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**Comment by elliottslaughter** [comment]
I'm starting to think this is related not to the LLVM version but something about how LLVM itself is being built. LLVM 9 used to pass, but suddenly started breaking in cff49cb29654c88e5d1ea3484e22bc77a80e58e2, and I needed to downgrade the dynamic tests to LLVM 8 with #490 in order to fix it again.

**Comment by ProfFan** [comment]
To chime in after so many years :) I remember this before, and it's because LLVM is loaded twice. The reason why it's loaded twice, I don't remember, but should be inside some issue comments.

**Comment by elliottslaughter** [comment]
This seems plausible, and I remember https://github.com/terralang/terra/issues/357#issuecomment-580408533. I guess the question is still where the second copy of LLVM is coming from, since (at least at the moment) we're still statically linking Clang, and I don't think that would pull in a second copy by itself.

**Comment by ProfFan** [comment]
https://github.com/CastXML/CastXML/issues/102

**Comment by elliottslaughter** [comment]
This seems to have gone away with the upgrade to Ubuntu 18.04. In general, I've begun to suspect that the Ubuntu packages are simply higher quality; LLVM's own packages seem to have intermittent issues. I'm increasingly inclined to upgrade Ubuntu more aggressively so we can stick with newer first-party packages.

Anyway, #534 confirms that this works in LLVM 9 and 10, so I'm going to consider this fixed as soon as that merges.
