### ISSUE TITLE
terra::terrain   - raster::terrain

### ISSUE THREAD

**Issue by salder** [terralang/terra#488]
Hi, 
using a 2m x 2m DEM I get values much larger than 90 degrees using the terrain function in terra. using the same data with the terrain function in raster the values  are max 90 degrees. 

hm.slope<-terra::terrain(hm, v="slope", neighbors=8, unit="degrees")
hm.slope
class       : SpatRaster 
dimensions  : 550, 550, 1  (nrow, ncol, nlyr)
resolution  : 2, 2  (x, y)
extent      : 640076, 641176, 7507928, 7509028  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
source      : memory 
name        :      slope 
min value   : 0.09442256 
max value   :   7036.305 

hm.r.slope<-raster::terrain(hm.r,opt="slope", neighbors=8, unit="degrees")
hm.r.slope
class      : RasterLayer 
dimensions : 550, 550, 302500  (nrow, ncol, ncell)
resolution : 2, 2  (x, y)
extent     : 640076, 641176, 7507928, 7509028  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs 
source     : memory
names      : slope 
values     : 0.09442247, 84.87707  (min, max)

Something with the terra::terrain function seems to be wrong?

Best regards
Sven

**Comment by elliottslaughter** [comment]
Hi,

Maybe this issue was intended for a different project? Our Terra is a programming language and doesn't have built-in terrain libraries.

**Comment by salder** [comment]
Hi, sorry you are right! It is R:terra… on gíthub…

Sven
