### ISSUE TITLE
Does terra support 16 bit string type ?

### ISSUE THREAD

**Issue by kcvinker** [terralang/terra#517]
Hi, 
terra looks nice to me. Can I use terra in win32 api programming ? It seems that we can call C functions in terra. And what about the support for wide string ? In win32 api, I would like to work with function names ended with a 'W', like CreateWindowExW. So it takes a LPCWSTR string. Is it possible in terra ? Thanks in advance.

**Comment by rongduo** [comment]
很高兴收到您的邮件，我会尽快处理的，谢谢。

**Comment by vinodvinu** [comment]
Thank you. :)

**Comment by elliottslaughter** [comment]
@rongduo Are you on an auto-responder? If so please shut it off.

@vinodvinu You can call any C APIs. If the C APIs support wide strings then you can call them to do what you need.

Terra doesn't have a _native_ wide string type. But neither does C. Terra in this sense has a level of abstraction very similar to C. You can make a `&int16` or a `int16[...]` or whatever as needed. The semantics will basically be the same as C. Terra doesn't even have any string functions built in so there's nothing you'll be missing.

**Comment by elliottslaughter** [comment]
I think the original question has been answered and there hasn't been a response to this in a couple of months, so I'm going to close this. If you run into anything else, please feel free to open a new issue or find us on zulip.

**Comment by kcvinker** [comment]
> I think the original question has been answered and there hasn't been a response to this in a couple of months, so I'm going to close this. If you run into anything else, please feel free to open a new issue or find us on zulip.

Okay. Thanks for your reply. :)
