### ISSUE TITLE
A PTX JIT compilation failed

### ISSUE THREAD

**Issue by yys123456** [terralang/terra#518]
Hello everyone, I am new to Terra. I follow the instruction to build Terra from source on Ubuntu 18.04.6 LTS, RTX2060, CUDA 11.3
I used the command below
`cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install .. -DTERRA_ENABLE_CUDA=ON `
`make install`
and add `build/bin/` to PATH in `.bashrc`, I went to `tests` folder and run `terra run all` and got the message (**first few lines**) below:
```
splitquote.t:
cudahello.t:
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
cudahello.t:23: cuModuleLoadData: cuda reported error 218: a PTX JIT compilation failed
stack traceback:
	[C]: in function 'error'
	[string "<string>"]:250: in function 'cudacompile'
	cudahello.t:23: in main chunk
```
**and the last few lines:**
```
=================
= FAILING tests
=================
cudahello.t
cudaglobal.t
cudaprintf.t
cudaoo.t
cudashared.t
cudaagg.t
cudaatomic.t
cudatex.t
cudatest.t
cudaconst2.t
cudaaggregate.t
cudaoffline.t
=================

525 tests passed. 12 tests failed.
```
exactly every test start with cuda failed

#### Video Card and CUDA information
![Screenshot from 2022-01-23 16-11-35](https://user-images.githubusercontent.com/42519504/150670070-59d7b3ff-880e-44d5-96a1-4c9f9ba474df.png)

**Comment by elliottslaughter** [comment]
What LLVM version are you using?

**Comment by yys123456** [comment]
@elliottslaughter 6.0
![Screenshot from 2022-01-25 18-57-00](https://user-images.githubusercontent.com/42519504/150964311-c7e4f773-f45c-4ec8-8cde-cc12e151d941.png)

**Comment by elliottslaughter** [comment]
@yys123456 Could you try a newer version? We support up to LLVM 13:

https://github.com/terralang/terra#supported-llvm-versions

I think the only issue is that the LLVM version used in your build is too old to support this generation of GPU.

**Comment by elliottslaughter** [comment]
I haven't seen a response to this in a couple of months, and I think the question has been answered. If there is anything else, please feel free to open a new issue or find us on zulip.
