### ISSUE TITLE
Migrate to opaque pointers

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#553]
Recent LLVM versions have begun migrating to opaque pointers, i.e., pointers with no type. Notably, LLVM 14 added versions of `CreateLoad` etc. that require an explicit type argument (as the element type is no longer specified in the pointer type).

For now, non-opaque pointers aren't actually gone so we can rely on the old code paths. But presumably at some point LLVM will pull the plug and we'll need to migrate.

My initial effort to do the migration didn't go so well because there are a bunch of corner cases. Not all types are clearly labeled in the compiler, and sometimes they seem to be missing entirely (because we're relying on pointers to carry that information). So in order to work in a world with opaque pointers, we need to track all of that and make sure we don't lose it as it's going down the stack.

**Comment by elliottslaughter** [comment]
This is now required as LLVM 15 has removed non-opaque pointers: https://releases.llvm.org/15.0.0/docs/ReleaseNotes.html#changes-to-the-llvm-ir

**Comment by rongduo** [comment]
很高兴收到您的邮件，我会尽快处理的，谢谢。

**Comment by elliottslaughter** [comment]
@rongduo you seem to be using an auto-responder on this issue tracker. Please stop. This is creating spam on the issues. I've seen this several times now and will need to block you if you don't disable the auto-responder.

**Comment by elliottslaughter** [comment]
Actually, it looks like we're going to be forced to straddle this change. According to the official documentation, opaque pointers in LLVM 14 are *not* production ready. So we'll need to keep the non-opaque code paths until we support LLVM 15+ only.

https://llvm.org/docs/OpaquePointers.html#version-support

**Comment by elliottslaughter** [comment]
The first part of this migration went into #639. I think at this point, there is only one nontrivial place in the code where we need pointer types:

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcompiler.cpp#L601-L603

This occurs in the context of trying to get external types out of Clang. Basically, we define a function that includes all of these types as arguments, and then when we need one, we grab that function and fetch the `N`th argument to get its type.

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcompiler.cpp#L598-L600

If you look for `llvm_definingfunction` you'll find it here:

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcwrapper.cpp#L147-L155

We're basically building a list of types:

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcwrapper.cpp#L122-L127

And we build a function with all the types as parameters:

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcwrapper.cpp#L501-L524

It's not totally clear to me whether we're hitting this line or not, but we may also be doing some magic to keep the function itself alive (or this might be for other functions):

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcwrapper.cpp#L483-L484

Anyway, it's not obvious to me how to replace this machinery. The types we're passing to the function are all `T*`, so under opaque pointers, we lose all type information. I tried passing just `T`, but (a) this crashes Clang (I'm not sure Clang is used to handling functions with so many non-pointer parameters), and (b) in the process of lowering to LLVM, Clang would mangle the types anyway (because parts of the C calling convention are implemented in Clang). Similarly I don't think passing any other type (`T[]`, `struct S { T t; }`, etc.) would work.

I think there are two things that a solution needs to accomplish:

 1. Make sure all imported types stay live so we can refer to them
 2. Make a way of passing them through to Terra so we can refer to the same types in our end

However, since I had to disable this code path in the past for other targets, I should also try disabling this conditional and see if we can get away with just not reusing the types at all:

https://github.com/terralang/terra/blob/8f43bed2bf8866799bbbe11e6e560f23b66d4e6d/src/tcompiler.cpp#L595-L597

I.e., treating every target as a non-native target.

**Comment by elliottslaughter** [comment]
We finished this in #643.
