### ISSUE TITLE
How to represent a C char

### ISSUE THREAD

**Issue by renatoathaydes** [terralang/terra#571]
I am trying to pass a C char to my C code.

Getting this error:

```
testing.t:11: pointer to int8 conversion loses precision
  Io.printf("Code of 'a' is %c", testingC.charToDigit([int8]('a')))
                                                               ^

stack traceback:
	[C]: in function 'error'
	/Users/runner/work/terra/terra/src/terralib.lua:396: in function 'finishandabortiferrors'
	/Users/runner/work/terra/terra/src/terralib.lua:3431: in function 'typecheck'
	/Users/runner/work/terra/terra/src/terralib.lua:1172: in function 'defineobjects'
	testing.t:9: in main chunk
```

I tried casting a single-char string like this: `[int8]('a')` as otherwise it treats `a` as a string pointer... also tried `'a'[0]` without luck.

**Comment by PyryM** [comment]
It's a bit cumbersome but you can turn a string literal of a single character into an integer on the Lua side, using Lua's `string.byte`:
```terra
var letter_a: int8 = [string.byte('a', 1)]
var letter_b: int8 = [('b'):byte(1)]
```

**Comment by elliottslaughter** [comment]
The issue is that `'a'` is a string, not a character. (In Lua both `'` and `"` are used for strings.)

So like @PyryM said, you need to figure out a way to get the value of the actual char. You can do that in Lua with `string.byte`, or you can use something like this in Terra itself:

```
'a'[0]
```

Which should *probably* get constant folded into simply the character.

More generally, all of Terra's literals are simply Lua literals (with a minor exception to distinguish between `1` and `1.0` so that the latter is a `double` while the former is an `int`). We don't currently have any syntax for literals outside of what Lua supports, so e.g. since Lua has no character type, Terra has no syntax to generate a literal of that kind.

And anyway, such literals would be kind of fraught anyway, since in this day and age you probably shouldn't assume everything is ASCII.

**Comment by renatoathaydes** [comment]
I misphrased that: Terra has bytes, `int8`... but not having a char literal makes it a nightmare to write code like what I am trying to do (probably lot of use cases). No need to downvote me , just try writing code to process stuff like HTTP which is ASCII-based or any other older protocol.

**Comment by elliottslaughter** [comment]
Sorry, the syntax is `('a')[0]`.

I guess after all these years I still get tripped up by Lua syntax. `var x = 'a'[0]` was getting interpreted as two statements, `var x = 'a'` and `0`.

```terra
terra main()
  var x = ('a')[0]
end
main:printpretty()
```

Output:

```
test_terra_bug_571.t:1: terra main() : {}
test_terra_bug_571.t:2:     var x : int8 = "a"[0]
test_terra_bug_571.t:1: end
```

**Comment by elliottslaughter** [comment]
About the issue of literals more generally: Terra, at least as it exists today, makes minimal changes to *Lua* syntax. The thing to keep in mind is that nearly all simple expressions get passed through to Lua. So when you write:

```terra
terra f(x : int)
  return x + 1
end
```

This is actually equivalent to writing:

```terra
terra f(x : int)
  return [x] + [1]
end
```

I.e., it's equivalent to escaping the `x` and the `1`. That may seem like a subtle difference, but it means that all literals and even variable references are Lua values first (and only become Terra values after being compiled into the code). So Terra inherits its literal syntax from Lua.

You could say, we'll let's just modify Lua to add a syntax for \<X>. But then you'd have a fork of Lua, which would make it harder to upgrade Lua later. You may recall the discussion of Lua versions from the other issue. It may be theoretically desirable to provide an option to switch to Lua (from LuaJIT) in the eventual future, and we can't do that if we have deep customization of LuaJIT. Or for that matter, we rely on a LuaJIT fork (Moonjit) for PPC64le support. That would all get a lot harder if we were in the habit of changing Lua's syntax.

P.S. And yeah, no need to downvote, folks. These are all legitimate questions.

**Comment by elliottslaughter** [comment]
Having said that, we could probably make a macro like `char('a')` that would be something like:

```terra
local char = macro(function(str)
  str = str:asvalue()
  assert(string.len(str) == 1)
  return `str[0]
end)

terra main()
  var x = char('a')
end
main:printpretty(false)
```

You can use this in the short term, and in the longer term, we could consider adding this to Terra so you don't need to.

**Comment by PyryM** [comment]
I usually use a non-macro function like
```terra
local function ascii(s)
  return s:byte()
end

local terra something()
  var x: int8 = [ascii('a')] -- the escape here is a little annoying
end
```

What would be convenient is if there were a macro variant that took its arguments as lua values rather than as quotes, but like a regular macro didn't need to be escaped.

**Comment by renatoathaydes** [comment]
Hey, thanks very much for the hints... but  I am quite happy with `('a')[0]` for now! If that gets too ugly I will use one of the suggestions above (I think `char('a')` goes well with the rest of the language and would be a good addition).

FYI the code I was writing looks like this:

```c
int char_to_digit(char c) {
  switch(tolower(c)) {
  case 'e':
    return 0;
  case 'j':
  case 'n':
  case 'q':
    return 1;
  case 'r':
  case 'w':
  case 'x':
    return 2;
  case 'd':
  case 's':
  case 'y':
    return 3;
  case 'f':
  case 't':
    return 4;
  case 'a':
  case 'm':
    return 5;
  case 'c':
  case 'i':
  case 'v':
    return 6;
  case 'b':
  case 'k':
  case 'u':
    return 7;
  case 'l':
  case 'o':
  case 'p':
    return 8;
  case 'g':
  case 'h':
  case 'z':
    return 9;
  default:
    return -1;
  }
}
```

Imagine writing this without anything similar to char literals :D but as you've shown, there are good enough alternatives so I am content again!
