### ISSUE TITLE
Update docs on Embedding Terra in C

### ISSUE THREAD

**Issue by renatoathaydes** [terralang/terra#573]
I tried to follow the guide https://terralang.org/getting-started.html#embedding-terra-lua-inside-of-c

A few things didn't work on Mac... so I am creating this issue to document what I had to do so maybe you can update the docs.

Here's what the docs say, currently:

```
# OSX
c++ simple.cpp -o simple -I<path-to-terra-folder>/terra/include \
-L<path-to-terra-folder>/lib -lterra \
-pagezero_size 10000 -image_base 100000000
```

I kept having issues with the linker. It couldn't find the terra dynlib. I use gcc but I believe the results are the same with any c compiler?!

Here's what I was trying:

```
▶ gcc simple.c -o simple -I$TERRAPATH/terra/include -L$TERRAPATH/lib -lterra -pagezero_size 10000 -image_base 100000000
simple.c:2:10: fatal error: 'terra.h' file not found
#include "terra.h"
         ^~~~~~~~~
1 error generated.
```

This was due to the include path being wrong, at least for me... it should be `include/terra`, not `terra/include`.

Fixing that, I got:

```
▶ gcc simple.c -o simple -I$TERRAPATH/include/terra -L$TERRAPATH/lib -lterra -pagezero_size 10000 -image_base 100000000
ld: library not found for -lterra
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This was because the name of the dynlib file was not following the pattern gcc wants.

```
▶ ls $TERRAPATH/lib    
libterra_s.a  terra.dylib
```

If I understand correctly, the name of the dylib file should've been `libterra.dylib`?!

After fixing that, it got past this problem and compilation worked:

```
▶ mv $TERRAPATH/lib/terra.dylib $TERRAPATH/lib/libterra.dylib

▶ gcc simple.c -o simple -I$TERRAPATH/include/terra -L$TERRAPATH/lib -lterra -pagezero_size 10000 -image_base 100000000         
ld: warning: Linking with PIE, -image_base will be ignored
```

But now, trying to run the binary wouldn't work:

```
▶ ./simple
dyld[91560]: Library not loaded: @rpath/terra.dylib
  Referenced from: /Users/renato/programming/experiments/terra/simple/simple
  Reason: tried: '/usr/local/lib/terra.dylib' (no such file), '/usr/lib/terra.dylib' (no such file)
[1]    91560 abort      ./simple
```

So I had to copy the dylib into my lib path like this, and it finally worked!

```
▶ cp $TERRAPATH/lib/libterra.dylib /usr/local/lib/terra.dylib                              

▶ echo "print('hello terra')" > hello.t

▶ ./simple hello.t                     
hello terra
```

Notice that I didn't need those numeric options:

```
▶ gcc simple.c -o simple -I$TERRAPATH/include/terra -L$TERRAPATH/lib -lterra                                           

▶ ./simple hello.t
hello terra
```

Hope this helps someone else :)

If I did something wrong, don't worry about it... otherwise, perhaps the docs could include some of this information.

**Comment by elliottslaughter** [comment]
@renatoathaydes Please try the build at https://github.com/elliottslaughter/terra/actions/runs/2551003972. That should at least fix the issue with `libterra.so` / `libterra.dylib`.

**Comment by elliottslaughter** [comment]
I believe this has been fixed, and I tweaked the docs to suggest linking `-lterra_s` (for static Terra).
