### ISSUE TITLE
Migrate to using LLVM's MCJIT

### ISSUE THREAD

**Issue by ohpauleez** [terralang/terra#58]
LLVM is beginning the process of replacing the current JIT with it's newer MCJIT.  While the version in 3.3 was a little buggy, it has been improved and stabilized in 3.4.

The main problem for Terra (and others) is that you can no longer add functions to a module once it is compiled.  MCJIT is multi-module (you can link references/call-sites across modules) so the common approach is place every function in its own module and judiciously use `prepare_call`/`prepare_global`.

Useful references include the [LLVM blog post](http://blog.llvm.org/2013/07/using-mcjit-with-kaleidoscope-tutorial.html) and [the follow-up](http://blog.llvm.org/2013/08/object-caching-with-kaleidoscope.html) on effective migration techniques, and the [recent pull-request for Julia](https://github.com/JuliaLang/julia/pull/5208) of a similar migration.

**Comment by Lupus** [comment]
@zdevito, I wonder how was the inlining issue fixed? I see a post on LLVM mailing list regarding this [1], but there seems to be no followup. Does enabling of MCJIT lead to performance penalty? As far as I can see debugging symbols only play nice (GDB is useful upon segfault) with MCJIT enabled.

[1] http://lists.llvm.org/pipermail/llvm-dev/2014-March/071304.html
