### ISSUE TITLE
Malformed mach-o on macOS 12.5 (M1)

### ISSUE THREAD

**Issue by shoe42** [terralang/terra#588]
Building using the default `-pagezero_size` and `-image_base` arguments results in an executable that cannot be executed (M1, macOS 12.5, LLVM 13, using LuaJIT commit https://github.com/LuaJIT/LuaJIT/commit/3065c910ad6027031aabe2dfd3c26a3d0f014b4f):

```sh
$ lldb ./bin/terra               
(lldb) target create "./bin/terra"
Current executable set to '.../terra/build/bin/terra' (arm64).
(lldb) r
error: Malformed Mach-o file
```

As per https://github.com/LuaJIT/LuaJIT/issues/649#issuecomment-751341864, are the flags still necessary with LuaJIT 2.1? Perhaps this isn't being caught in the tests due to the binary not actually being executed?

https://github.com/terralang/terra/blob/4e58e686aea7ffb513818c918a955a0ad023f64c/travis.sh#L248-L253

**Comment by elliottslaughter** [comment]
We test on x86 Mac all the time (both in CI and locally). So I guess this is an ARM64 issue.

The lines you linked to are for the "plain" tests, but we always run in CMake (except on Windows).

https://github.com/terralang/terra/blob/4e58e686aea7ffb513818c918a955a0ad023f64c/travis.sh#L242-L245

If you'd like to send a PR to delete these lines, I'd be happy to take it if it passes:

https://github.com/terralang/terra/blob/8bf225f3d9cacfdf4fb1b7393e6baf2deb4b0d15/src/CMakeLists.txt#L330-L336

https://github.com/terralang/terra/blob/8bf225f3d9cacfdf4fb1b7393e6baf2deb4b0d15/GNUmakefile#L176-L179

**Comment by elliottslaughter** [comment]
If it would help to pin https://github.com/LuaJIT/LuaJIT/commit/3065c910ad6027031aabe2dfd3c26a3d0f014b4f, I'd be happy to take a PR for that too.
