### ISSUE TITLE
Failed to find headers with clitools clang on macOS 12.5 (M1)

### ISSUE THREAD

**Issue by shoe42** [terralang/terra#590]
On an M1 mac, running macOS 12.5 and with clitools version 13.0.0.0.1.1627064638, if you try and use the stock clitools clang, the build process fails to find some headers - see below log. My current workaround is to use clang from Homebrew's `llvm@13`.

Failing build:
```sh
$ CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX="$(pwd)/../install" -DCMAKE_PREFIX_PATH='/opt/homebrew/opt/llvm@13' -DTERRA_ENABLE_CUDA=OFF ..
```

Running `make` a 2nd time to try and just get the errors outputs the following:
```sh
$ make -j8
[  0%] Generating luajit/lib/libluajit-5.1.a, luajit/lib/libluajit-5.1.dylib, luajit/bin/luajit-2.1.0-beta3, luajit/include/luajit-2.1/lua.h, luajit/include/luajit-2.1/lualib.h, luajit/include/luajit-2.1/lauxlib.h, luajit/include/luajit-2.1/luaconf.h
==== Building LuaJIT 2.1.0-beta3 ====
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[ 80%] Built target LLVMObjectFiles
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_fold.o
HOSTCC    host/buildvm_lib.o
CC        lj_gc.o
CC        lj_obj.o
CC        lj_char.o
In file included from host/buildvm_fold.c:In file included from 6host/buildvm_lib.c:
:6host/buildvm.h:9:10: fatal error: 'sys/types.h' file not found
:
host/buildvm.h:9:10: #include <sys/types.h>
         ^~~~~~~~~~~~~
In file included from fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
host/buildvm_peobj.c:9:
host/buildvm.h:9:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
host/minilua.c:34:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.
make[4]: *** [host/buildvm_peobj.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from host/buildvm_asm.c:6:
host/buildvm.h:9:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
make[4]: *** [host/buildvm_fold.o] Error 1
In file included from lj_gc.c:12:
In file included from ./lj_obj.h:13:
./lj_def.h:45:10: fatal error: 'string.h' file not found
#include <string.h>
         ^~~~~~~~~~
1 error generated.
make[4]: *** [host/buildvm_lib.o] Error 1
1 error generated.
make[4]: *** [host/buildvm_asm.o] Error 1
In file included from lj_obj.c:9:
In file included from ./lj_obj.h:13:
./lj_def.h:45:10: fatal error: 'string.h' file not found
#include <string.h>
         ^~~~~~~~~~
In file included from lj_char.c:22:
In file included from ./lj_char.h:9:
./lj_def.h:45:10: fatal error: 'string.h' file not found
#include <string.h>
         ^~~~~~~~~~
1 error generated.
1 error generated.
make[4]: *** [lj_char.o] Error 1
make[4]: *** [lj_obj.o] Error 1
1 error generated.
make[4]: *** [lj_gc.o] Error 1
1 error generated.
make[4]: *** [host/minilua.o] Error 1
make[3]: *** [src/luajit] Error 2
make[2]: *** [luajit/lib/libluajit-5.1.a] Error 2
make[1]: *** [CMakeFiles/LuaJIT.dir/all] Error 2
make: *** [all] Error 2
```

Some other info:
```sh
$ clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```sh
$ xcodebuild -version
Xcode 13.4.1
Build version 13F100
```

**Comment by elliottslaughter** [comment]
Does it help if you build with:

```
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
```

**Comment by elliottslaughter** [comment]
For what it's worth, I confirmed that I get this error on my x86 Mac when I `unset SDKROOT` (which I normally have set as shown above).

**Comment by elliottslaughter** [comment]
A while back, macOS removed `/usr/include`. We had a big discussion on that in #365, but the end result was that, as best we can tell, `SDKROOT` is the standard way to specify where the development toolkit is located.

As best I can  tell, Apple Clang does not need this to be set, because they add custom code on top of vanilla Clang to auto-detect it. In contrast, if you build a vanilla Clang, it will not (by default) detect this; but it will read `SDKROOT` if you set it. It may be that Homebrew is setting up a configuration variable in Clang to set this automatically, or else do something the vanilla Clang isn't doing.

But as for the reason why the error occurs with Apple Clang: the auto-detection seems to be finicky. For some reason I don't fully understand, when we use the full path to the C compiler (as we need to do to build LuaJIT), the auto-detection gets shut off. So even though Apple Clang should auto-detect it, you need to set `SDKROOT` to make the LuaJIT build work. (Or maybe there is something specific to how the LuaJIT build works, I'm not sure. I haven't really dug too deep into this.) Terra itself should build fine because it's just using the Apple Clang compiler as normal.

But at any rate, you will need `SDKROOT` set in order for Terra itself to work because it has the same issues as a vanilla Clang.

**Comment by elliottslaughter** [comment]
By the way, I'd be curious how the test suite looks on M1. You could run either `ctest -j4` on a CMake build directory or `../build/bin/terra ./run` from the `tests` directory and paste the bottom part of the output (where it shows test pass rate and failing tests).

**Comment by elliottslaughter** [comment]
Hm, this failure rate makes me think you might have forgotten `SDKROOT`? Or something similar.

We pass 100% of tests on all x86 platforms: macOS, Linux, FreeBSD, and Windows. We also pass 100% of tests on PPC64le Linux.

On ARM Linux, the pass rate is around 96% (https://github.com/terralang/terra/issues/565#issuecomment-1153306721). Even in emulation I get 95% pass rate (https://github.com/terralang/terra/issues/565#issuecomment-1153471338).

I'm hoping that there's a simple fix (like `SDKROOT`) that gets you up to a similar pass rate.

**Comment by elliottslaughter** [comment]
I can't explain why `SDKROOT` wouldn't be working, but that failure mode looks *exactly* like what I'd expect if `SDKROOT` weren't set.

You might be able to work around with:

```
export INCLUDE_PATH="$(xcrun --sdk macosx --show-sdk-path)/usr/include"
```

That's a different way of specifying the path and shouldn't be necessary if `SDKROOT` is set. But it might work if `SDKROOT` isn't.

You built with an LLVM from Homebrew, right? It may also be worth trying a vanilla LLVM (there's a build recipe here: https://github.com/terralang/terra#instructions-for-building-llvm-from-source).

**Comment by elliottslaughter** [comment]
Thanks. It's good to know we at least have a path to getting it mostly working.

I'd be surprised if `SDKROOT` parsing is really dependent on x86, but I suppose it's possible. (If so, probably an oversight.) My only other idea is to try a vanilla source build since Homebrew does sometimes add patches to their packages. (And again, instructions at https://github.com/terralang/terra#instructions-for-building-llvm-from-source .)

**Comment by elliottslaughter** [comment]
@shoe42 by the way, if you pull from master, you should (hopefully) see a higher test pass rate now that #593 has merged.

**Comment by elliottslaughter** [comment]
Thanks for testing.

I should have mentioned #597. On Linux, this means that AArch64 only works with LLVM 11. I suspect this would help you fix most or all of these outstanding failures.
